SERVER_NAME = test-bi
BI_ROOT_PASSWORD = password

DEV_USER = root
DEV_HOST = 127.0.0.1
DEV_DATABASE = simplewiki
DEV_PASSWORD = password
DEV_PORT = 6000
DEV_MYSQL_PORT = 3306


dev:
	DB_HOST=$(DEV_HOST) \
	DB_USER=$(DEV_USER) \
	DB_PASSWORD=$(DEV_PASSWORD) \
	DB_DATABASE=$(DEV_DATABASE) \
	DB_PORT=$(DEV_PORT) \
	npm run start:dev

tests:
	DB_HOST=$(HOST) \
	DB_USER=$(USER) \
	DB_PASSWORD=$(PASSWORD) \
	DB_DATABASE=$(DATABASE) \
	DB_PORT=$(PORT) \
	npm run test:watch
